/**
 * Investor registration form validation schema
 */

import { z } from 'zod';
import {
	INVESTOR_CONSTANTS,
	NAME_RULES,
	REGION_RULES,
	BANK_NAME_RULES,
	NATIONAL_ID_RULES,
	AGE_RULES,
	VALIDATION_MESSAGES,
} from '../../constants/investor.constants';

export const investorFormSchema = z.object({
	first_name: z
		.string()
		.min(1, VALIDATION_MESSAGES.FIRST_NAME.REQUIRED)
		.min(NAME_RULES.MIN_LENGTH, VALIDATION_MESSAGES.FIRST_NAME.MIN_LENGTH)
		.max(NAME_RULES.MAX_LENGTH, VALIDATION_MESSAGES.FIRST_NAME.MAX_LENGTH)
		.regex(NAME_RULES.PATTERN, VALIDATION_MESSAGES.FIRST_NAME.INVALID),
	father_name: z
		.string()
		.min(1, VALIDATION_MESSAGES.FATHER_NAME.REQUIRED)
		.min(NAME_RULES.MIN_LENGTH, VALIDATION_MESSAGES.FATHER_NAME.MIN_LENGTH)
		.max(NAME_RULES.MAX_LENGTH, VALIDATION_MESSAGES.FATHER_NAME.MAX_LENGTH)
		.regex(NAME_RULES.PATTERN, VALIDATION_MESSAGES.FATHER_NAME.INVALID),
	family_name: z
		.string()
		.min(1, VALIDATION_MESSAGES.FAMILY_NAME.REQUIRED)
		.min(NAME_RULES.MIN_LENGTH, VALIDATION_MESSAGES.FAMILY_NAME.MIN_LENGTH)
		.max(NAME_RULES.MAX_LENGTH, VALIDATION_MESSAGES.FAMILY_NAME.MAX_LENGTH)
		.regex(NAME_RULES.PATTERN, VALIDATION_MESSAGES.FAMILY_NAME.INVALID),
	grandfather_name: z
		.string()
		.min(1, VALIDATION_MESSAGES.GRANDFATHER_NAME.REQUIRED)
		.min(NAME_RULES.MIN_LENGTH, VALIDATION_MESSAGES.GRANDFATHER_NAME.MIN_LENGTH)
		.max(NAME_RULES.MAX_LENGTH, VALIDATION_MESSAGES.GRANDFATHER_NAME.MAX_LENGTH)
		.regex(NAME_RULES.PATTERN, VALIDATION_MESSAGES.GRANDFATHER_NAME.INVALID),
	birth_date: z
		.string()
		.min(1, VALIDATION_MESSAGES.BIRTH_DATE.REQUIRED)
		.refine(
			(date) => {
				const birthDate = new Date(date);
				const today = new Date();
				const age = today.getFullYear() - birthDate.getFullYear();
				return age >= AGE_RULES.MIN && age <= AGE_RULES.MAX;
			},
			{ message: VALIDATION_MESSAGES.BIRTH_DATE.INVALID_AGE }
		),
	national_id: z
		.string()
		.min(1, VALIDATION_MESSAGES.NATIONAL_ID.REQUIRED)
		.regex(NATIONAL_ID_RULES.PATTERN, VALIDATION_MESSAGES.NATIONAL_ID.INVALID),
	email: z
		.string()
		.min(1, VALIDATION_MESSAGES.EMAIL.REQUIRED)
		.email(VALIDATION_MESSAGES.EMAIL.INVALID),
	phone: z
		.string()
		.min(1, VALIDATION_MESSAGES.PHONE.REQUIRED),
	national_address_email: z
		.string()
		.min(1, VALIDATION_MESSAGES.NATIONAL_ADDRESS_EMAIL.REQUIRED)
		.email(VALIDATION_MESSAGES.NATIONAL_ADDRESS_EMAIL.INVALID),
	region: z
		.string()
		.min(1, VALIDATION_MESSAGES.REGION.REQUIRED)
		.min(REGION_RULES.MIN_LENGTH, VALIDATION_MESSAGES.REGION.MIN_LENGTH)
		.max(REGION_RULES.MAX_LENGTH, VALIDATION_MESSAGES.REGION.MAX_LENGTH),
	iban: z
		.string()
		.min(1, VALIDATION_MESSAGES.IBAN.REQUIRED),
	bank_name: z
		.string()
		.min(1, VALIDATION_MESSAGES.BANK_NAME.REQUIRED)
		.min(BANK_NAME_RULES.MIN_LENGTH, VALIDATION_MESSAGES.BANK_NAME.MIN_LENGTH)
		.max(BANK_NAME_RULES.MAX_LENGTH, VALIDATION_MESSAGES.BANK_NAME.MAX_LENGTH),
	amount: z
		.string()
		.min(1, VALIDATION_MESSAGES.AMOUNT.REQUIRED)
		.refine(
			(val) => {
				const amount = parseFloat(val);
				return !isNaN(amount) && amount >= INVESTOR_CONSTANTS.MIN_AMOUNT && amount <= INVESTOR_CONSTANTS.MAX_AMOUNT;
			},
			{ message: VALIDATION_MESSAGES.AMOUNT.INVALID }
		),
	agreed: z
		.boolean()
		.refine((val) => val === true, {
			message: VALIDATION_MESSAGES.AGREED.REQUIRED,
		}),
});
