export const MODULE_SPEC = {
	hypermarket: {
		bg: "#E3FFE8",
		darkBg: "#1a3d24",
		text: "#237030",
		darkText: "#6fcf87",
		label: "هايبر ماركت شلة",
		tall: true,
		disabled: false,
		textAlign: "right" as const,
		iconOpacity: 0.5,
	},
	restaurants: {
		bg: "#FFF1E7",
		darkBg: "#3d2a1a",
		text: "#B56717",
		darkText: "#f0a85c",
		label: "المطـــاعم",
		tall: true,
		disabled: false,
		textAlign: "right" as const,
		iconOpacity: 0.5,
	},
	cafe: {
		bg: "#F6F0E9",
		darkBg: "#352a22",
		text: "#A06A42",
		darkText: "#d4a574",
		label: "المقـــاهي",
		tall: false,
		disabled: false,
		textAlign: "right" as const,
		iconOpacity: 1,
		iconSrc: "/modules/cafe.png",
	},
	markets: {
		bg: "#F5F6F4",
		darkBg: "#2a2d2b",
		text: "#555555",
		darkText: "#9ca3af",
		label: "أسواق الحــي",
		soonLabel: "قريباً",
		tall: false,
		disabled: true,
		textAlign: "right" as const,
		iconOpacity: 0.5,
		iconSrc: "/modules/markets.png",
	},
	pharmacy: {
		bg: "#F5F6F4",
		darkBg: "#2a2d2b",
		text: "#555555",
		darkText: "#9ca3af",
		label: "الصيدليات",
		soonLabel: "قريباً",
		tall: false,
		disabled: true,
		textAlign: "right" as const,
		iconOpacity: 0.5,
		iconSrc: "/modules/pharmacy.png",
	},
} as const;

export type ModuleSpecKey = keyof typeof MODULE_SPEC;
