export const MODULE_SPEC = {
	hypermarket: {
		id: 3,
		bg: "#E3FFE8",
		darkBg: "#1a3d24",
		text: "#237030",
		darkText: "#6fcf87",
		label: { ar: "هايبر ماركت شلة", en: "Shella Hypermarket" },
		tall: true,
		disabled: false,
		textAlign: "start" as const,
		iconOpacity: 0.5,
		iconSrc: "/modules/hyper.png",
	},
	restaurants: {
		id: 6,
		bg: "#FFF1E7",
		darkBg: "#3d2a1a",
		text: "#B56717",
		darkText: "#f0a85c",
		label: { ar: "المطـــاعم", en: "Restaurants" },
		tall: true,
		disabled: false,
		textAlign: "start" as const,
		iconOpacity: 0.5,
		iconSrc: "/modules/resturants.png",
	},
	cafe: {
		id: 9,
		bg: "#F6F0E9",
		darkBg: "#352a22",
		text: "#A06A42",
		darkText: "#d4a574",
		label: { ar: "المقـــاهي", en: "Cafes" },
		tall: false,
		disabled: false,
		textAlign: "start" as const,
		iconOpacity: 1,
		iconSrc: "/modules/cafe.png",
	},
	markets: {
		id: 7,
		bg: "#F5F6F4",
		darkBg: "#2a2d2b",
		text: "#555555",
		darkText: "#9ca3af",
		label: { ar: "أسواق الحــي", en: "Neighborhood markets" },
		soonLabel: { ar: "قريباً", en: "Coming soon" },
		tall: false,
		disabled: true,
		textAlign: "start" as const,
		iconOpacity: 0.5,
		iconSrc: "/modules/markets.png",
	},
	pharmacy: {
		id: 8,
		bg: "#F5F6F4",
		darkBg: "#2a2d2b",
		text: "#555555",
		darkText: "#9ca3af",
		label: { ar: "الصيدليات", en: "Pharmacies" },
		soonLabel: { ar: "قريباً", en: "Coming soon" },
		tall: false,
		disabled: true,
		textAlign: "start" as const,
		iconOpacity: 0.5,
		iconSrc: "/modules/pharmacy.png",
	},
} as const;

export type ModuleSpecKey = keyof typeof MODULE_SPEC;

export const MODULE_SPEC_BY_ID: Record<number, ModuleSpecKey> = {
	[MODULE_SPEC.hypermarket.id]: "hypermarket",
	[MODULE_SPEC.restaurants.id]: "restaurants",
	[MODULE_SPEC.cafe.id]: "cafe",
	[MODULE_SPEC.markets.id]: "markets",
	[MODULE_SPEC.pharmacy.id]: "pharmacy",
};
