/** Profile copy — centralised for future i18n wiring. */
export const PROFILE_STRINGS = {
    pageTitle: "حسابي",
    accountSettings: "إعدادات الحساب",
    welcome: (name: string) => `أهلاً ${name}`,
    yourPoints: "نقاطك",
    myWallet: "محفظتي",
    qidhaWallet: "محفظة قيدها",
    earnPointsNow: "اربح نقاط الآن",
    addBalanceNow: "أضف رصيد الآن",
    subscribeNow: "اشترك الآن",
    sectionMyAccount: "حسابي",
    deliveryAddresses: "عناوين التوصيل",
    language: "اللغة",
    languageAr: "العربية (المملكة العربية السعودية)",
    languageEn: "English (US)",
    darkMode: "تفعيل الوضع الداكن",
    notifications: "الإشعارات",
    sectionPromo: "النشاط الترويجي والأرباح",
    coupons: "الكوبونات",
    statistics: "إحصائيات",
    earnWithFriends: "اكسب مع مشاركة الأصدقاء",
    joinAsDriver: "انضم كرجل توصيل",
    voucherRep: "مندوب تسويق قسائم شرائية",
    sectionHelp: "المساعدة والدعم",
    liveChat: "الدردشة الحية",
    technicalSupport: "المساعدة والدعم الفني",
    checkUpdates: "التحقق من التحديثات",
    aboutUs: "معلومات عنا",
    sectionLegal: "المستندات القانونية",
    privacy: "الخصوصية",
    terms: "الشروط والأحكام",
    refundPolicy: "سياسة استرداد الأموال",
    logout: "تسجيل الخروج",
    editTitle: "إعدادات الحساب",
    name: "الاسم",
    email: "البريد الالكتروني",
    phone: "رقم الهاتف",
    phoneNotEditable: "(غير قابل للتعديل)",
    gender: "الجنس",
    selectGender: "اختار الجنس",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    deleteAccount: "حذف الحساب",
    save: "حفظ",
    genderPageTitle: "تحديد الجنس",
    chooseGender: "اختر جنسك",
    genderHelper: "نستخدم هذه المعلومة لتحسين تجربتك داخل التطبيق.",
    photoTitle: "صورة الملف الشخصي",
    photoGuidanceTitle: "يرجى التأكد من أن الصورة:",
    photoGuidance1: "لا توجد بالصورة أي ضبابية والإضاءة بها جيدة",
    photoGuidance2: "دون نظارات أو قبعات أو أي اكسسوارات أخرى",
    deleteTitle: "حذف الحساب",
    deleteIntro: "يرجى مراجعة المعلومات التالية بعناية قبل حذف حسابك.",
    deleteBody:
        "سيؤدي هذا الإجراء إلى حذف حسابك بشكل نهائي، بالإضافة إلى إزالة بعض البيانات المرتبطة به، مثل:",
    deleteWarning: "لا يمكن التراجع عن هذا الإجراء بعد تنفيذه.",
    deleteAgree: "لقد قرأت البيان أعلاه وأوافق عليه",
    logoutConfirmTitle: "هل أنت متأكد أنك تريد تسجيل الخروج ؟",
    logoutConfirmYes: "نعم ، تسجيل خروج",
    cancel: "إلغاء",
    loginRequiredTitle: "هذه الخدمة تتطلب تسجيل دخول",
    loginRequiredSubtitle: "الرجاء تسجيل الدخول للاستمتاع بخدمتك",
    login: "تسجيل الدخول",
    qidhaSubscribeTitle: "الاشتراك في قيدها المطلوب",
    qidhaSubscribeBody: "لاستخدام محفظة قيدها ، يجب الاشتراك وتفعيل المحفظة أولاً",
    updateSuccess: "تم حفظ التغييرات بنجاح",
    updateError: "تعذر حفظ التغييرات، حاول مرة أخرى",
    deleteSuccess: "تم حذف حسابك",
    deleteError: "تعذر حذف الحساب، حاول مرة أخرى",
    requiredField: "هذا الحقل مطلوب",
    invalidPhoto: "يرجى اختيار صورة JPG أو PNG بحجم أقل من 5 ميجابايت",
    invalidEmail: "يرجى إدخال بريد إلكتروني صحيح",
    invalidName: "يرجى إدخال الاسم",
    missingPhone: "رقم الهاتف غير متوفر في حسابك",
} as const;

export const LOCALE_COOKIE = "app_locale";

export type AppLocale = "ar" | "en";

export const LOCALE_LABELS: Record<AppLocale, string> = {
    ar: PROFILE_STRINGS.languageAr,
    en: PROFILE_STRINGS.languageEn,
};
