import type { Order } from "@/features/my-orders/types/orders.types";

export const MOCK_ORDERS: Order[] = [
    {
        id: 1,
        storeName: "مطعم البيك",
        storeDescription: "وجبات سريعة ومشويات",
        orderNum: "#1234",
        date: "25 أكتوبر 2025",
        orderDate: "25 أكتوبر 2025، 1:30 م",
        status: "completed",
        total: "85 SAR",
        subtotal: "75 SAR",
        deliveryFee: "5 SAR",
        serviceFee: "5 SAR",
        discount: "0 SAR",
        paymentMethod: "Credit Card · 4242",
        orderAddress: "حي النزهة، شارع الملك فهد، الرياض",
        module: "restaurants",
        items: [
            { id: 1, name: "برجر دجاج", description: "مع صوص خاص وخس وطماطم", price: "35 SAR", originalPrice: "45 SAR", quantity: 1 },
            { id: 2, name: "بطاطس كبيرة", description: "مقلية بزيت نباتي مع الصلصة", price: "20 SAR", quantity: 1 },
            { id: 3, name: "كولا 500 مل", description: "مشروب غازي بارد", price: "8 SAR", quantity: 2 },
            { id: 4, name: "تشيز كيك", description: "قطعة تشيز كيك بالفراولة", price: "22 SAR", quantity: 1 },
        ],
    },
    {
        id: 2,
        storeName: "هايبر ماركت شلة",
        storeDescription: "سوبرماركت متكامل",
        orderNum: "#1235",
        date: "24 أكتوبر 2025",
        orderDate: "24 أكتوبر 2025، 11:10 ص",
        status: "preparing",
        total: "156 SAR",
        subtotal: "140 SAR",
        deliveryFee: "10 SAR",
        serviceFee: "6 SAR",
        discount: "0 SAR",
        paymentMethod: "Credit Card · 1234",
        orderAddress: "حي العليا، شارع التحلية، الرياض",
        module: "hyper",
        items: [
            { id: 1, name: "أرز بسمتي5 كجم", description: "أرز هندي فاخر طويل الحبة", price: "45 SAR", quantity: 2 },
            { id: 2, name: "زيت زيتون 750 مل", description: "زيت زيتون بكر ممتاز", price: "38 SAR", originalPrice: "50 SAR", quantity: 1 },
            { id: 3, name: "مياه معدنية 12 زجاجة", description: "مياه نقية باردة", price: "12 SAR", quantity: 1 },
        ],
    },
    {
        id: 3,
        storeName: "ستاربكس",
        storeDescription: "مشروبات ومقهى",
        orderNum: "#1236",
        date: "23 أكتوبر 2025",
        orderDate: "23 أكتوبر 2025، 3:45 م",
        status: "cancelled",
        total: "45 SAR",
        subtotal: "38 SAR",
        deliveryFee: "7 SAR",
        serviceFee: "0 SAR",
        discount: "0 SAR",
        paymentMethod: "Credit Card · 5678",
        orderAddress: "حي الملز، طريق الملك عبدالعزيز، الرياض",
        module: "cafes",
        items: [
            { id: 1, name: "لاتيه كبير", description: "لاتيه بالحليب الكامل الدسم", price: "22 SAR", quantity: 1 },
            { id: 2, name: "كيك موكا", description: "قطعة كيك بالشوكولاتة والقهوة", price: "16 SAR", quantity: 1 },
        ],
    },
    {
        id: 4,
        storeName: "مطعم الرومانسية",
        storeDescription: "مأكولات شرقية فاخرة",
        orderNum: "#1237",
        date: "22 أكتوبر 2025",
        orderDate: "22 أكتوبر 2025، 8:00 م",
        status: "completed",
        total: "230 SAR",
        subtotal: "200 SAR",
        deliveryFee: "15 SAR",
        serviceFee: "15 SAR",
        discount: "20 SAR",
        paymentMethod: "Credit Card · 9012",
        orderAddress: "حي الروضة، شارع الأمير سلطان، جدة",
        module: "restaurants",
        items: [
            { id: 1, name: "مشاوي مشكلة", description: "كباب، شيش طاووق، كفتة", price: "120 SAR", quantity: 1 },
            { id: 2, name: "سلطة فتوش", description: "خضار طازجة مع خبز محمص", price: "25 SAR", quantity: 2 },
            { id: 3, name: "خبز تنور", description: "خبز طازج من الفرن", price: "5 SAR", quantity: 3 },
        ],
    },
    {
        id: 5,
        storeName: "كوفي دي",
        storeDescription: "قهوة مختصة وحلويات",
        orderNum: "#1238",
        date: "21 أكتوبر 2025",
        orderDate: "21 أكتوبر 2025، 10:20 ص",
        status: "completed",
        total: "62 SAR",
        subtotal: "52 SAR",
        deliveryFee: "10 SAR",
        serviceFee: "0 SAR",
        discount: "0 SAR",
        paymentMethod: "Credit Card · 3456",
        orderAddress: "حي السليمانية، شارع العروبة، الرياض",
        module: "cafes",
        items: [
            { id: 1, name: "كابتشينو مزدوج", description: "قهوة مختصة بالحليب المبخر", price: "28 SAR", quantity: 1 },
            { id: 2, name: "كيك ريد فيلفت", description: "كيك محلي بالكريمة البيضاء", price: "24 SAR", originalPrice: "30 SAR", quantity: 1 },
        ],
    },
    {
        id: 6,
        storeName: "مطعم الأصيل",
        storeDescription: "أكلات شعبية سعودية",
        orderNum: "#1239",
        date: "20 أكتوبر 2025",
        orderDate: "20 أكتوبر 2025، 12:30 م",
        status: "preparing",
        total: "180 SAR",
        subtotal: "160 SAR",
        deliveryFee: "10 SAR",
        serviceFee: "10 SAR",
        discount: "0 SAR",
        paymentMethod: "Credit Card · 7890",
        orderAddress: "حي الورود، شارع الإمام سعود، الرياض",
        module: "restaurants",
        items: [
            { id: 1, name: "كبسة دجاج", description: "أرز بسمتي مع دجاج مشوي وبهارات", price: "80 SAR", quantity: 1 },
            { id: 2, name: "مرق", description: "مرق لحم طازج مع الخضار", price: "35 SAR", quantity: 1 },
            { id: 3, name: "سلطة خضراء", description: "خس، طماطم، خيار، زيتون", price: "18 SAR", quantity: 1 },
            { id: 4, name: "لبن رائب", description: "لبن طازج بارد", price: "8 SAR", quantity: 2 },
        ],
    },
];
